import { PROMO_CODE_STATUS } from '../constants/promoCodeStatus.js';

// Shared by Product and ConsultationPlan — `price` is always the raw,
// admin-edited base price; this is the amount actually charged once a
// discount is applied. Rounded to 2 decimals, matching the precision prices
// are entered/displayed with elsewhere in this app.
export const computeDiscountedPrice = (price, discountPercent) =>
    discountPercent > 0 ? Math.round(price * (1 - discountPercent / 100) * 100) / 100 : price;

// Shared response shapes so User/Admin documents are serialized the same
// way everywhere they're returned (auth, admin user management, etc).
export const toPublicUser = (user) => ({
    id: user._id,
    name: user.name,
    email: user.email,
    phone: user.phone,
    status: user.status,
    // Derived rather than stored: accounts with a googleId signed up (or later
    // linked) via "Sign in with Google"; everyone else registered in-app.
    provider: user.googleId ? 'google' : 'app',
    referralCode: user.referralCode,
    createdAt: user.createdAt,
});

export const toPublicAdmin = (admin) => ({
    id: admin._id,
    name: admin.name,
    email: admin.email,
    role: admin.role,
    status: admin.status,
    createdAt: admin.createdAt,
});

export const toPublicOrder = (order) => ({
    id: order._id,
    orderNumber: order.orderNumber,
    user: order.user,
    items: order.items,
    // Orders placed before promo codes existed have no subtotal stored —
    // fall back to the total, which was the pre-discount amount back then.
    subtotal: order.subtotal ?? order.total,
    discountAmount: order.discountAmount ?? 0,
    promoCode: order.promoCode?.code
        ? { code: order.promoCode.code, discountPercent: order.promoCode.discountPercent }
        : null,
    total: order.total,
    paymentMethod: order.paymentMethod,
    transactionId: order.transactionId,
    screenshotAttached: order.screenshotAttached,
    shipping: order.shipping,
    status: order.status,
    placedAt: order.createdAt,
});

// `image` is duplicated as the first entry of `images` because the app's
// ProductCard reads product.image while the detail gallery reads images[].
export const toPublicProduct = (product) => ({
    id: product._id,
    slug: product.slug,
    name: product.name,
    category: product.category,
    price: product.price,
    discountPercent: product.discountPercent ?? 0,
    // Amount actually charged — the app shows `price` struck through beside
    // this whenever discountPercent > 0.
    discountedPrice: computeDiscountedPrice(product.price, product.discountPercent ?? 0),
    stock: product.stock,
    description: product.description,
    nutritionFacts: product.nutritionFacts ?? [],
    variants: product.variants ?? [],
    image: product.images?.[0],
    images: product.images ?? [],
    rating: product.rating,
    reviews: product.reviewCount,
    reviewCount: product.reviewCount,
    status: product.status,
    // Auto-generated by Product.model.js — the app reads this straight into
    // generateMetadata() and JSON-LD.
    seo: {
        metaTitle: product.seo?.metaTitle,
        metaDescription: product.seo?.metaDescription,
        keywords: product.seo?.keywords ?? [],
        headline: product.seo?.headline,
        imageAlt: product.seo?.imageAlt,
    },
    createdAt: product.createdAt,
    updatedAt: product.updatedAt,
});

export const toPublicBlog = (blog) => ({
    id: blog._id,
    title: blog.title,
    slug: blog.slug,
    category: blog.category,
    author: blog.author,
    excerpt: blog.excerpt,
    content: blog.content ?? '',
    readTime: blog.readTime,
    image: blog.image,
    // The app renders `date` as a plain YYYY-MM-DD string.
    date: blog.publishedAt?.toISOString().slice(0, 10),
    // Full timestamps for Article structured data and sitemap lastModified.
    publishedAt: blog.publishedAt,
    status: blog.status,
    // Auto-generated by Blog.model.js — consumed by the app's generateMetadata.
    seo: {
        metaTitle: blog.seo?.metaTitle,
        metaDescription: blog.seo?.metaDescription,
        keywords: blog.seo?.keywords ?? [],
        imageAlt: blog.seo?.imageAlt,
        wordCount: blog.seo?.wordCount,
    },
    createdAt: blog.createdAt,
    updatedAt: blog.updatedAt,
});

export const toPublicReply = (reply) => ({
    id: reply._id,
    authorType: reply.authorType,
    authorName: reply.authorName,
    message: reply.message,
    createdAt: reply.createdAt,
});

// `forUser` is the id of the requesting user (omitted for the admin panel,
// which has no per-user read state to report).
export const toPublicNotification = (notification, forUser) => ({
    id: notification._id,
    title: notification.title,
    message: notification.message,
    type: notification.type,
    audience: notification.audience,
    status: notification.status,
    date: notification.sendDate?.toISOString().slice(0, 10),
    sendDate: notification.sendDate,
    isRead: forUser ? notification.readBy?.some((id) => String(id) === String(forUser)) ?? false : undefined,
    createdAt: notification.createdAt,
});

// Reuses the same shape as review replies — both are just
// {authorType, authorName, message, createdAt} threads.
export const toPublicConsultation = (consultation) => ({
    id: consultation._id,
    user: consultation.user,
    goal: consultation.goal,
    plan: consultation.plan,
    personalInfo: consultation.personalInfo,
    goalData: consultation.goalData,
    uploads: consultation.uploads,
    transactionId: consultation.transactionId,
    status: consultation.status,
    assignedDate: consultation.assignedDate,
    conversation: (consultation.conversation ?? []).map(toPublicReply),
    submittedAt: consultation.createdAt,
    createdAt: consultation.createdAt,
    updatedAt: consultation.updatedAt,
});

export const toPublicCategory = (category) => ({
    id: category._id,
    name: category.name,
    slug: category.slug,
    status: category.status,
});

// Same discount shape as toPublicProduct: `price` is the admin-edited base
// price, `discountedPrice` the amount actually charged.
export const toPublicConsultationPlan = (plan) => ({
    id: plan._id,
    goal: plan.goal,
    label: plan.label,
    durationMonths: plan.durationMonths,
    price: plan.price,
    priceSAR: plan.priceSAR ?? 0,
    priceUSD: plan.priceUSD ?? 0,
    // Each currency carries its own discount percent (see ConsultationPlan
    // model) — never share one across currencies here.
    discountPercent: plan.discountPercent ?? 0,
    discountPercentSAR: plan.discountPercentSAR ?? 0,
    discountPercentUSD: plan.discountPercentUSD ?? 0,
    discountedPrice: computeDiscountedPrice(plan.price, plan.discountPercent ?? 0),
    discountedPriceSAR: computeDiscountedPrice(plan.priceSAR ?? 0, plan.discountPercentSAR ?? 0),
    discountedPriceUSD: computeDiscountedPrice(plan.priceUSD ?? 0, plan.discountPercentUSD ?? 0),
    features: plan.features ?? [],
    isPaused: plan.isPaused ?? false,
});

export const toPublicCareer = (career) => ({
    id: career._id,
    title: career.title,
    description: career.description,
    link: career.link,
    email: career.email,
    isOpen: career.isOpen ?? true,
    createdAt: career.createdAt,
});

// `career` is expected to be populated with at least `title` by the calling
// controller (admin list view); it's the raw ObjectId right after creation.
export const toPublicCareerApplication = (application) => ({
    id: application._id,
    career: application.career?.title
        ? { id: application.career._id, title: application.career.title }
        : { id: application.career },
    name: application.name,
    email: application.email,
    phone: application.phone,
    resumeLink: application.resumeLink,
    referralName: application.referralName,
    referralEmail: application.referralEmail,
    referralPhone: application.referralPhone,
    createdAt: application.createdAt,
});

export const toPublicSubscriber = (subscriber) => ({
    id: subscriber._id,
    email: subscriber.email,
    createdAt: subscriber.createdAt,
});

// `referrer`/`referredUser` are expected to be populated with at least
// `name email createdAt` by the calling controller.
export const toPublicReferralCommission = (commission) => ({
    id: commission._id,
    referrer: commission.referrer && {
        id: commission.referrer._id,
        name: commission.referrer.name,
        email: commission.referrer.email,
    },
    referredUser: commission.referredUser && {
        id: commission.referredUser._id,
        name: commission.referredUser.name,
        email: commission.referredUser.email,
        joinedAt: commission.referredUser.createdAt,
    },
    consultationBooked: commission.consultationBooked,
    productBought: commission.productBought,
    status: commission.status,
    amount: commission.amount,
    proofScreenshot: commission.proofScreenshot,
    notes: commission.notes,
    sentAt: commission.sentAt,
    createdAt: commission.createdAt,
    updatedAt: commission.updatedAt,
});

// `owner`/`issuedFor`/`usedByUser` are only expanded when the calling
// controller populated them (the admin list does; the app's own-codes list
// doesn't need to).
export const toPublicPromoCode = (promo) => ({
    id: promo._id,
    code: promo.code,
    // Reported from the date rather than the stored field so a code reads as
    // expired the moment it lapses, not once the lazy sweep flips it (see
    // promoCode.util.js#expireStalePromoCodes).
    status:
        promo.status === PROMO_CODE_STATUS.ACTIVE && promo.expiresAt <= new Date()
            ? PROMO_CODE_STATUS.EXPIRED
            : promo.status,
    discountPercent: promo.discountPercent,
    minOrderTotal: promo.minOrderTotal ?? 0,
    expiresAt: promo.expiresAt,
    usedAt: promo.usedAt,
    discountAmount: promo.discountAmount,
    owner: promo.owner?.name ? { id: promo.owner._id, name: promo.owner.name, email: promo.owner.email } : undefined,
    issuedFor: promo.issuedFor?.name
        ? { id: promo.issuedFor._id, name: promo.issuedFor.name, email: promo.issuedFor.email }
        : undefined,
    usedOnOrder: promo.usedOnOrder?.orderNumber
        ? { id: promo.usedOnOrder._id, orderNumber: promo.usedOnOrder.orderNumber }
        : undefined,
    createdAt: promo.createdAt,
});

export const toPublicPromoSettings = (settings) => ({
    enabled: settings.enabled,
    discountPercent: settings.discountPercent,
    validityDays: settings.validityDays,
    minOrderTotal: settings.minOrderTotal,
    shareable: settings.shareable,
    updatedAt: settings.updatedAt,
});

export const toPublicReview = (review) => ({
    id: review._id,
    // Populated documents expose _id; unpopulated ones are the raw ObjectId.
    productId: review.product?._id ?? review.product,
    productName: review.product?.name,
    userId: review.user?._id ?? review.user,
    name: review.userName,
    rating: review.rating,
    comment: review.comment,
    replies: (review.replies ?? []).map(toPublicReply),
    date: review.createdAt?.toISOString().slice(0, 10),
    createdAt: review.createdAt,
});
